site_name: "My Project Documentation"
theme:
  name: material

nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/overview.md
      - Installation: getting-started/installation.md
  - Services:
      - PostgreSQL: services/postgres.md
      - PgAdmin: services/pgadmin.md
      - ETL: services/etl.md
  - License: license.md

markdown_extensions:
  - toc:
      permalink: true
  - codehilite:
      linenums: true
