site_name: "Marketing Analytics Project Documentation"
theme:
  name: material

nav:
  - Home: index.md
  - Feedback: feedback.md
  - Services:
      - PostgreSQL: services/postgres.md
      - PgAdmin: services/pgadmin.md
      - ETL: services/etl.md
  - Roadmap: roadmap.png
  - ERD:
      - New ERD: newERD.pdf
  - Readme: readme.md
markdown_extensions:
  - toc:
      permalink: true
  - codehilite:
      linenums: true
